data: dict = {
    "dummy": {
        "dummy": [
            {
                "hashtags": "#MarketingApp #SocialMediaPosts #Quotes #randomquotes #quoteoftheday #instaquotes #quotestoliveby #quotesandsayings #quotesaboutlife #quotesgram",
                "p_name": "buildaudience.ai",
                "post_url": "https://storage.googleapis.com/captionai-4b64a.appspot.com/1.png",
                "quote": "Technology is a useful servant but a dangerous master",
                "quote_author": "Simon Mainwaring",
                "tag": "Make your social media posts stand out with buildaudience.ai!"
            },
            {
                "hashtags": "#MarketingApp #SocialMediaPosts #Quotes #randomquotes #quoteoftheday #instaquotes #quotestoliveby #quotesandsayings #quotesaboutlife #quotesgram",
                "p_name": "buildaudience.ai",
                "post_url": "https://storage.googleapis.com/captionai-4b64a.appspot.com/2.png",
                "quote": "Technology is always a two-edged sword. It will bring in many benefits, but also many disasters",
                "quote_author": "Marc Andreessen",
                "tag": "Make your marketing work smarter, not harder!"
            },
            {
                "hashtags": "#MarketingApp #SocialMediaPosts #Quotes #randomquotes #quoteoftheday #instaquotes #quotestoliveby #quotesandsayings #quotesaboutlife #quotesgram",
                "p_name": "buildaudience.ai",
                "post_url": "https://storage.googleapis.com/captionai-4b64a.appspot.com/3.png",
                "quote": "My theme for philanthropy is the same approach I used with technology: to find a need and fill it",
                "quote_author": "Chris Milk",
                "tag": "Marketing made easy."
            }
        ]
    },
    "quote_of_the_day": {
        "post_url": [
            "https://storage.googleapis.com/captionai-4b64a.appspot.com/1.png",
            "https://storage.googleapis.com/captionai-4b64a.appspot.com/2.png",
            "https://storage.googleapis.com/captionai-4b64a.appspot.com/3.png"
        ],
        "qotd": "Love is the absence of judgment.",
        "qotd_author": "Dalai Lama",
    },
    "quotes": {
        "naval": [
            "Earn with your mind, not your time.",
            "Rich people get paid by the project and pay by the hour.",
            "If being ethical were profitable everybody would do it.",
            "You're never going to get rich renting out your time.",
            "Following your genuine intellectual curiosity is a better foundation for a career than following whatever is making money right now.",
            "Building a following on Twitter is building a castle out of sand, as the implacable tide shifts in and out. Invest in the free and open web blogs, podcasts, newsletters.",
            "Collecting airline miles is coupon-clipping for the middle class.",
            "You want to be rich and anonymous, not poor and famous.",
            "All the benefits in life come from compound interest money, relationships, habits anything of importance.",
            "Making money through an early lucky trade is the worst way to win. The bad habits that it reinforces will lead to a lifetime of losses.",
            "Smart money is just dumb money that's been through a crash.",
            "Wealth creation is an evolutionarily recent positive-sum game. Status is an old zero-sum game. Those attacking wealth creation are often just seeking status.",
            "The real struggle isn't proletariat vs bourgeois. It's between high-status elites and wealthy elites. When their cooperation breaks, revolution.",
            "There are no get rich quick schemes. That's just someone else getting rich off you.",
            "Children are happy because: 1) They're not self conscious 2) They lack a sense of time pressure 3) They've no goals. The bottom line is they are living from moment to moment, and the mind is not there to interfere in their bliss.",
            "Tell your friends that you're a happy person. Then you'll be forced to conform to it. You'll have a consistency bias. You have to live up to it. Your friends will expect you to be a happy person.",
            "The fundamental delusion there is something out there that will make me happy and fulfilled forever.",
            "If you want to be successful, surround yourself with people who are more successful than you are, but if you want to be happy, surround yourself with people who are less successful than you are.",
            "I don't plan. I'm not a planner. I prefer to live in the moment and be free and to flow and to be happy.",
            "The most important trick to be happy is to realize that happiness is a choice that you make and a skill that you develop. You choose to be happy, and then you work at it. It's just like building muscles.",
            "Happiness is a state where nothing is missing.",
            "Happiness is a choice and a skill and you can dedicate yourself to learning that skill and making that choice.",
            "When building habits, choose consistency over the content. The best book is the one you can't put down. The best exercise is the one you enjoy doing every day. The best health food is the one you find tasty. The best work is the work you'd do for free.",
            "True happiness comes out of peace. Peace comes out of many things, but it comes from fundamentally understanding yourself.",
            "Sing the song that only you can sing, write the book that only you can write, build the product that only you can build… live the life that only you can live.",
            "Your goal in life is to find out the people who need you the most, to find out the business that needs you the most, to find the project and the art that needs you the most. There is something out there just for you.",
            "To be honest, speak without identity.",
            "Every moment has to be complete in and of itself.",
            "When it comes to medicine and nutrition, subtract before you add.",
            "Caught in a funk? Use meditation, music, and exercise to reset your mood. Then choose a new path to commit emotional energy for rest of day.",
            "Nothing you do is going to matter that much in the long run. Don't take yourself so seriously.",
            "If you can't see yourself working with someone for life, don't work with them for a day.",
            "This is such a short and precious life that it's really important that you don't spend it being unhappy.",
            "If you're desensitized to the fact that you're going to die, consider it a different way. As far as you're concerned, this world is going to end. Now what.",
            "My 1 repeated learning in life: 'There Are No Adults' Everyone's making it up as they go along. Figure it out yourself, and do it.",
            "Humans are basically habit machines… I think learning how to break habits is actually a very important meta-skill and can serve you in life almost better than anything else.",
            "People who live far below their means enjoy a freedom that people busy upgrading their lifestyles can't fathom.",
            "All the real benefits of life come from compound interest.",
            "Sophisticated foods are bittersweet (wine, beer, coffee, chocolate). Addictive relationships are cooperative and competitive. Work becomes flow at the limits of ability. The flavor of life is on the edge.",
            "So I have no time for short-term things: dinners with people I won't see again, tedious ceremonies to please tedious people, traveling to places that I wouldn't go to on vacation.",
            "A personal metric: how much of the day is spent doing things out of obligation rather than out of interest.",
            "The distant future is small free cities with drone armies and skill-based immigration policies, surrounded by a sea of failed socialist states.",
            "Wondering how long until social media-induced mental illnesses start getting recognized and treated.",
            "If you eat, invest, and think according to what the news advocates, you'll end up nutritionally, financially and morally bankrupt.",
            "Perhaps one reason why yoga and meditation are hard to sustain is that they have no extrinsic value. Purely single player games.",
            "Wisdom is really about figuring the long-term consequences of your actions.",
            "If you aren't curious about it, you'll never be good at it.",
            "Inspiration is perishable act on it immediately.",
            "You can have the mind or you can have the moment.",
            "Signaling virtue is a vice.",
            "It's almost always possible to be honest and positive.",
            "The right to debate should not be up for debate.",
            "A rational person can find peace by cultivating indifference to things outside of their control.",
            "Yoga cultivates Peace of Body. Meditation cultivates Peace of Mind.",
            "Better to find a new audience than to write for the audience.",
            "Before you can lie to another, you must first lie to yourself.",
            "All greatness comes from suffering.",
            "Watch every thought. Always ask, why am I having this thought.",
            "Enlightenment is the space between your thoughts.",
            "Clear thinkers appeal to their own authority.",
            "You make your own luck if you stay at it long enough.",
            "I don't have time is just saying it's not a priority.",
            "Truth is that which has predictive power.",
            "We say peace of mind, but really what we want is peace from the mind.",
            "The secret to public speaking is to speak as if you were alone.",
            "Lots of literacy in modern society, but not enough numeracy.",
            "Information is everywhere but its meaning is created by the observer that interprets it. Meaning is relative and there is no objective, overarching meaning.",
            "Morality and ethics automatically emerge when we realize the long term consequences of our actions.",
            "People spend too much time doing and not enough time thinking about what they should be doing.",
            "Desire is a contract that you make with yourself to be unhappy until you get what you want.",
            "People who try to look smart by pointing out obvious exceptions actually signal the opposite.",
            "The people who succeed are irrationally passionate about something.",
            "If you try to micromanage yourself all you're going to do is make yourself miserable.",
            "If it entertains you now but will bore you someday, it's a distraction. Keep looking.",
            "The older the problem, the older the solution.",
            "The problem happens when we have multiple desires. When we have fuzzy desires. When we want to do ten different things and we're not clear about which is the one we care about.",
            "Think clearly from the ground up. Understand and explain from first principles. Ignore society and politics. Acknowledge what you have. Control your emotions.",
            "Don't do things that you know are morally wrong. Not because someone is watching, but because you are. Self-esteem is just the reputation that you have with yourself.",
            "Cynicism is easy. Mimicry is easy. Optimistic contrarians are the rarest breed.",
            "You can change it, you can accept it, or you can leave it. What is not a good option is to sit around wishing you would change it but not changing it, wishing you would leave it but not leaving it, and not accepting it. It's that struggle, that aversion, that is responsible for most of our misery. The phrase that I use the most to myself in my head is one word: accept.",
            "Anger is a hot coal that you hold in your hand while waiting to throw it at someone else.",
            "A contrarian isn't one who always objects that's a conformist of a different sort. A contrarian reasons independently, from the ground up, and resists pressure to conform.",
            "The first rule of handling conflict is don't hang around people who are constantly engaging in conflict.",
            "Objectively, the world is improving. To the elites, it's falling apart as their long-lived institutions are flattened by the Internet.",
            "We feel guilt when we no longer want to associate with old friends and colleagues who haven't changed. The price, and marker, of growth.",
            "If you hurt other people because they have an expectation of you that's their problem. If they have an agreement from you that's yours",
            "There's a theory that I call 'the five chimps theory'. In Zoology, you can predict the mood and behavior patterns of any chimp by which five chimps they hang out with the most. Choose your five chimps carefully.",
            "Knowledge is a skyscraper. You can take a shortcut with a fragile foundation of memorization, or build slowly upon a steel frame of understanding.",
            "Teaching is more a way for the teacher to learn than for the student to learn.",
            "The overeducated are worse off than the undereducated, having traded common sense for the illusion of knowledge.",
            "You get rewarded for unique knowledge, not for effort. Effort is required to create unique knowledge.",
            "Free education is abundant, all over the internet. It's the desire to learn that's scarce.",
            "If the primary purpose of the school was education, the Internet should obsolete it. But the school is mainly about credentialing.",
            "The power to make and break habits and learning how to do that is really important.",
            "One of the most damaging and widespread social beliefs is the idea that most adults are incapable of learning new skills.",
            "Even today, what to study and how to study it are more important than where to study it and for how long. The best teachers are on the Internet. The best books are on the Internet. The best peers are on the Internet. The tools for learning are abundant. It's the desire to learn that's scarce.",
            "Someone who is using a lot of fancy words and big concepts probably doesn't know what they're talking about. The smartest people can explain things to a child; if you can't do that, you don't understand the concept.",
            "Study microeconomics, game theory, psychology, persuasion, ethics, mathematics, and computers.",
            "Knowledge is either from direct experience or from verifiable, falsifiable science. There is knowledge that is transmitted but not verifiable / falsifiable, and this knowledge is indistinguishable from that which is false.",
            "Specific knowledge is found by pursuing your genuine curiosity and passion rather than whatever is hot right now.",
            "Reading my old blog posts makes me cringe. The posturing is so obvious.",
            "Reading is more efficient when at rest. Audio is more efficient when in motion.",
            "Technology is the application of knowledge to control the natural world. It's the greatest driver of both human prosperity and our capacity for self-annihilation.",
            "Technology is not only the thing that moves the human race forward, but it's the only thing that ever has. Without technology, we're just monkeys playing in the dirt.",
            "Technology is applied science. Science is the study of nature. Mathematics is the language of nature. Philosophy is the root of mathematics. All tightly interrelated.",
            "The variation between engineering output is so high that the best engineers will always be underpaid, and driven towards founding companies.",
            "Ego is false confidence, self-respect is true confidence.",
            "School, politics, sports, and games train us to compete against others. True rewards wealth, knowledge, love, fitness, and equanimity come from ignoring others and improving ourselves.",
            "A fit body, a calm mind, a house full of love. These things cannot be bought they must be earned.",
            "Love is given, not received.",
            "If you don't love yourself who will.",
            "Escape competition through authenticity.",
            "Learn to sell. Learn to build. If you can do both, you will be unstoppable.",
            "Who you do business with is just as important as what you choose to do.",
            "The Efficient Markets Hypothesis fails because humans are herd animals, not independent rational actors. Thus the best investors tend to be antisocial and contrarian.",
            "Branding requires accountability. To build a great personal brand (an eponymous one), you must take on the risk of being publicly wrong.",
            "If you're more passionate about founding a business than the business itself, you can fall into a ten-year trap. Better to stay emotionally unattached and select the best opportunity that arises. Applies to relationships too.",
            "Don't debate people in the media when you can debate them in the marketplace.",
            "Social media has degenerated into a deafening cacophony of groups signaling and repeating their shared myths.",
            "Above product-market fit is founder-product-market fit.",
            "No meetings before 11 am. No meetings when emails or calls will do. Don't schedule calls, text coordinate them on the fly when possible. Cram all meetings into two days a week. 1-on-1s are usually 30-minute walking meetings. (Meetings are the death of productivity)",
            "VCs and universities are both in the business of hunting black swans. They filter the applicant funnel, the brand selected candidates, and harvest the winner's rep to further enlarge the funnel.",
            "Set and enforce an aspirational personal hourly rate. If fixing a problem will save less than your hourly rate, ignore it. If outsourcing a task will cost less than your hourly rate, outsource it.",
            "Develop 'strategic incompetence' people won't ask you to do things you hate to do, if you're bad at them.",
            "Become the best in the world at what you do. Keep redefining what you do until this is true.",
            "The better the reviewed knows the reviewer, the kinder the review. Negative reviews get rarer as you go from Amazon to Yelp to AirBnB.",
            "Our mission is to help founders and anyone or anything that helps founders helps us with our mission.",
            "Entrepreneurship is really hard and painful I'm not sure I'd recommend it for anyone who can't handle the extreme stress.",
            "The best founders are extremely thoughtful and have an eye for quality. I don't know if there's any generic advice here that would be helpful. Startup knowledge is a moving target."
        ],
        "technology": [
            "Technology is best when it brings people together. Matt Mullenweg ",
            "The science of today is the technology of tomorrow. Edward Teller ",
            "Technology is a useful servant but a dangerous master. Christian Lous Lange ",
            "Every once in a while, a new technology, an old problem, and a big idea turn into an innovation. Dean Kamen ",
            "New technology is not good or evil in and of itself. It's all about how people choose to use it. David Wong ",
            "Technology and social media have brought power back to the people. Mark McKinnon ",
            "Sharing is good, and with digital technology, sharing is easy. Richard Stallman ",
            "Technology, like art, is a soaring exercise of the human imagination. Daniel Bell ",
            "While technology is important, it's what we do with it that truly matters. Muhammad Yunus ",
            "The only constant in the technology industry is change. Marc Benioff ",
            "It has become appallingly obvious that our technology has exceeded our humanity. Unknown ",
            "Information technology is at the core of how you do your business and how your business model itself evolves. Satya Nadella ",
            "Technological progress has merely provided us with more efficient means for going backwards. Aldous Huxley ",
            "The further you get into technology, the further you go into gaming. That's the general rule. Nick Johnson ",
            "Technology is cool, but you've got to use it as opposed to letting it use you. Prince ",
            "Innovation in an existing company is not just the sum of great technology, key acquisitions, or smart people. Corporate innovation needs a culture that matches and supports it. Steve Blank ",
            "Social media is not about the exploitation of technology but service to community. Simon Mainwaring ",
            "Our world is built on biology and once we begin to understand it, it then becomes a technology. Ryan Bethencourt ",
            "Even when you take a holiday from technology, technology doesn't take a break from you. Douglas Coupland ",
            "We can't blame the technology when we make mistakes. Tim Berners-Lee ",
            "Science and technology are the keys to both our longevity and our demise. Our entire existence on this planet is a double-edged sword. Rhys Darby ",
            "Technology gives us the facilities that lessen the barriers of time and distance - the telegraph and cable, the telephone, radio, and the rest. Emily Greene Balch ",
            "Virtual reality is a technology that could actually allow you to connect on a real human level, soul-to-soul, regardless of where you are in the world. Chris Milk ",
            "Information technology has been one of the leading drivers of globalization, and it may also become one of its major victims. Evgeny Morozov ",
            "Technology is unlocking the innate compassion we have for our fellow human beings. Bill Gates ",
            "Our technology, our machines, is part of our humanity. We created them to extend ourselves, and that is what is unique about human beings. Ray Kurzweil ",
            "Especially in technology, we need revolutionary change, not incremental change. Larry Page ",
            "For a successful technology, reality must take precedence over public relations, for Nature cannot be fooled. Richard P. Feynman ",
            "Universal coverage, not medical technology, is the foundation of any caring health care system. Richard Lamm ",
            "There is no technology today that cannot be defeated by social engineering. Frank Abagnale ",
            "All of technology, really, is about maximizing free options. Nassim Nicholas Taleb ",
            "If science fiction is the mythology of modern technology, then its myth is tragic. Ursula K. Le Guin ",
            "All of our technology is completely unnecessary to a happy life. Tom Hodgkinson ",
            "Humanity is acquiring all the right technology for all the wrong reasons. R. Buckminster Fuller ",
            "Every aspect of human technology has a dark side, including the bow and arrow. Margaret Atwood ",
            "Technology and robotics are advancing and will reduce the need for workers in the future. Jan C. Ting ",
            "Technology makes the world a new place. Shoshana Zuboff ",
            "Once a new technology rolls over you, if you're not part of the steamroller, you're part of the road. Stewart Brand ",
            "I think technology really increased human ability. But technology cannot produce compassion. Dalai Lama ",
            "Like all technology, social media is neutral but is best put to work in the service of building a better world. Simon Mainwaring ",
            "The technology keeps moving forward, which makes it easier for the artists to tell their stories and paint the pictures they want. George Lucas ",
            "If you think technology can solve your security problems, then you don't understand the problems and you don't understand the technology. Bruce Schneier ",
            "Technology is always a two-edged sword. It will bring in many benefits, but also many disasters. Alan Moore ",
            "Many people mistakenly think a new technology cancels out an old one. Judith Martin ",
            "Technology feeds on itself. Technology makes more technology possible. Alvin Toffler ",
            "Technology is huge; I wanted to learn about it. People might say that's odd, but I think it's odd if artists aren't interested in the world around them. I'm always chasing that. Bono ",
            "Technology is only meaningful when it reaches the people. Pranav Mistry ",
            "We are often celebrating technology and codes, but we don't really think about the creative side. Harper Reed ",
            "Technology, outsourcing, a growing temp staffing industry, productivity efficiencies, have all replaced the middle class. James Altucher ",
            "Technology advances at exponential rates, and human institutions and societies do not. They adapt at much slower rates. Those gaps get wider and wider. Mitch Kapor ",
            "Technology makes things faster and more cost-effective, but it's not perfect. It requires you to be as flexible as you can be. John Phillips ",
            "Technology is how we create wealth, how we cure diseases, how we'll build an environment that's sustainable and also gives people the capacity to pull more out of this world and still leave it better than when they found it. Dean Kamen ",
            "Technology should be an important ingredient. It may be and should be a tool for social development. Aleksander Kwasniewski ",
            "As technology tries to maintain its dizzying ascent, one dead weight has kept its altitude in check: the battery. Steven Levy ",
            "Technology gives us power, but it does not and cannot tell us how to use that power. Jonathan Sacks ",
            "The technology at the leading edge changes so rapidly that you have to keep current after you get out of school. I think probably the most important thing is having good fundamentals. Gordon Moore ",
            "Technology is changing the way we interact as humans. Dan Brown ",
            "Technology... is a queer thing. It brings you great gifts with one hand, and it stabs you in the back with the other. Carrie Snow ",
            "Technology is destructive only in the hands of people who do not realize that they are one and the same process as the universe. Alan Watts ",
            "Technology changes all the time; human nature, hardly ever. Evgeny Morozov ",
            "The latest technology is not always good for anything except to the producers of the technology. Wendell Berry ",
            "Our lifetime may be the last that will be lived out in a technological society. Arthur C. Clarke ",
            "Making a moonshot is almost more an exercise in creativity than it is in technology. Astro Teller ",
            "Technology is, of course, a double edged sword. Fire can cook our food but also burn us. Jason Silva ",
            "AI might be a powerful technology, but things won't get better simply by adding AI. Vivienne Ming ",
            "I see technology as being an extension of the human body. David Cronenberg ",
            "Technology is making gestures precise and brutal, and with them men. Theodor Adorno ",
            "Technology is changing so fast that knowledge about specifics can quickly become obsolete. That's why so much of what technicians learn is on the job. Robert Reich ",
            "Technology requires knowledge and expertise more than it requires money. Jonathan Raymond ",
            "My theme for philanthropy is the same approach I used with technology: to find a need and fill it. An Wang ",
            "With any advent in technology, any technological innovation, there is the good and the bad. Henry Rollins ",
            "The art challenges the technology, and the technology inspires the art. John Lasseter ",
            "Technology is vital. We have to have development in new technology if we're going to solve these environmental problems without throwing humanity back in poverty. Ramez Naam ",
            "You are cruising along, and then technology changes. You have to adapt. Marc Andreessen ",
            "Because of the rate of technology change, forecast horizons are shrinking. Steve Jurvetson ",
            "If information wants to be free, then that's true everywhere, not just in information technology. Mitch Kapor ",
            "Science and technology multiply around us. To an increasing extent they dictate the languages in which we speak and think. Either we use those languages, or we remain mute. J. G. Ballard ",
            "Technology determines the possibilities of society. Iain Banks ",
            "Civilization depends on our expanding ability to produce food efficiently, which has markedly accelerated thanks to science and technology. Nina Fedoroff ",
            "If you're not looking toward the future or trying to improve the current technology, you'll be left behind. Gwynne Shotwell ",
            "Wherever technology reaches its real fulfillment, it transcends into architecture. Ludwig Mies van der Rohe ",
            "Technology is teaching us to be human again. Simon Mainwaring ",
            "If you run from technology, it will chase you. Robert M. Pirsig ",
            "Computing technology started out as number-crunching. Ramez Naam ",
            "Technology is characterized by constant change, rapid innovation, creative destruction, and revolutionary products. Marsha Blackburn ",
            "People gravitate to what they believe to be popular... Technology is enabling even more of that. Bob Iger ",
            "Technology improves our lives in so many ways - from our toasters, ovens, and refrigerators at home to our computers, fax machines, and BlackBerrys at work. Technology makes once-burdensome tasks easy and fun. Jared Polis ",
            "Technology is neutral, but it all depends on the way we use it. Jean-Michel Jarre ",
            "I don't think its good for the soul to invest too much of yourself in technology. David Thewlis ",
            "We know that the hardest work is to keep yourself open to the world that technology hasn't tamed. Laura Esquivel ",
            "The human condition today is better than it's ever been, and technology is one of the reasons for that. Tom Clancy ",
            "You cannot make thousands of universities or hundreds of thousands of professors, but with technology and the Internet you can have great courses and make a digital university. Carlos Slim ",
            "If you look at, you know, the limitations of creating new products, you're only limited by the technology that you have to work with. Homaro Cantu ",
            "If you look at all the technology we're interconnected with every day, all this complex technology that connects humanity, it actually doesn't connect us. Chris Milk ",
            "I don't think that technology is going to allow for greater subjugation of people. I think it's gonna give them more freedom. Palmer Luckey ",
            "Technology can be a great equalizer when it comes to health care, education - to the point where rich, poor, middle class can all get the same benefits. Jeff Greene ",
            "If you create open technology that people can use, adapt and play with, it builds capability and they teach themselves. Charles Leadbeater ",
            "Mechanization best serves mediocrity. Frank Lloyd Wright ",
            "Changes call for innovation, and innovation leads to progress. Li Keqiang ",
            "Some people think technology has the answers. Kevin Mitnick ",
            "Technology itself is neither good nor bad. People are good or bad. Naveen Jain ",
            "In some ways, technology keeps on enhancing us, and we embrace it. Ramez Naam ",
            "The great growling engine of change - technology. Alvin Toffler ",
            "Exploration is the engine that drives innovation. Innovation drives economic growth. So let's all go exploring. Edith Widder ",
            "Technology may create a condition, but the questions are what do we do about ourselves. We better understand ourselves pretty clearly and we better find ways to like ourselves. Herbert Simon ",
            "Technology is the knack of so arranging the world that we don't have to experience it. Max Frisch ",
            "Technology has to be invented or adopted. Jared Diamond ",
        ]
    }
}
