import React from 'react'
import { useMediaQuery, Container, Link, Typography, Stack, IconButton, Box, useTheme } from '@mui/material';
import FacebookIcon from '@mui/icons-material/Facebook';
import TwitterIcon from '@mui/icons-material/Twitter';
import InstagramIcon from '@mui/icons-material/Instagram';
import LinkedInIcon from '@mui/icons-material/LinkedIn';

const BlogPostFooter = () => {
    const matchDownSM = useMediaQuery((theme) => theme.breakpoints.down('sm'));
    const socials = [
        <IconButton key={1} href="https://www.facebook.com/BuildAudience" target="_blank" rel="noreferrer" size="small" sx={{ color: 'primary.main' }}>
            <FacebookIcon />
        </IconButton>,
        <IconButton key={2} href="https://twitter.com/BuildAudience" target="_blank" rel="noreferrer" size="small" sx={{ color: 'primary.main' }}>
            <TwitterIcon />
        </IconButton>,
        <IconButton key={3} href="https://www.linkedin.com/company/buildaudience/" target="_blank" rel="noreferrer" size="small" sx={{ color: 'primary.main' }}>
            <InstagramIcon />
        </IconButton>,
        <IconButton key={4} href="https://www.instagram.com/buildaudience/" target="_blank" rel="noreferrer" size="small" sx={{ color: 'primary.main' }}>
            <LinkedInIcon />
        </IconButton>
    ]
    const theme = useTheme()
    return (
        <Box
            justifyContent='center'
            alignItems='center'
            display='flex'
            minHeight='200px'
            backgroundColor={`${theme.palette.secondary.main}`}
            mt={3}
        >
            <Box width='100%'>
                <Container maxWidth="xl">
                    <Stack
                        pt={2}
                        pb={2}
                        direction={matchDownSM ? 'column' : 'row'}
                        justifyContent={matchDownSM ? 'center' : 'space-between'}
                        spacing={2}
                        textAlign={matchDownSM ? 'center' : 'inherit'}
                    >
                        <Stack
                            direction={matchDownSM ? 'column' : 'row'}
                            spacing={matchDownSM ? 1 : 3}
                            textAlign={matchDownSM ? 'center' : 'inherit'}
                            alignItems='center'
                        >
                            <Typography
                                variant="h5"
                                color="primary"
                                component={Link}
                                href="https://material-ui.com/store/contributors/codedthemes/"
                                target="_blank"
                                underline="hover"
                            >
                                More Blogs
                            </Typography>
                            <Typography
                                variant="h5"
                                color="primary"
                                component={Link}
                                href="https://codedthemes.com"
                                target="_blank"
                                underline="hover"
                            >
                                Privacy Policy
                            </Typography>
                            <Typography
                                variant="h5"
                                color="primary"
                                component={Link}
                                href="https://codedthemes.support-hub.io/"
                                target="_blank"
                                underline="hover"
                            >
                                Support
                            </Typography>
                        </Stack>
                        <Box
                            justifyContent={matchDownSM ? 'center' : ''}
                            sx={{
                                display: 'flex',
                                flexDirection: 'row',
                                alignItems: 'center',
                                '& > *': {
                                    m: 1,
                                },
                            }}
                        >
                            {socials}
                        </Box>
                    </Stack>
                    <Stack
                        pt={2}
                        pb={2}
                        direction={matchDownSM ? 'column' : 'row'}
                        justifyContent={matchDownSM ? 'center' : 'start'}
                        spacing={2}
                        textAlign='center'
                    >
                        <Typography variant="h5" color="primary" component="span" sx={{ letterSpacing: '1px' }}>
                            &copy; Blog generated By&nbsp;
                            <Typography component={Link} variant="h5" href="https://codedthemes.com" target="_blank" underline="hover">
                                BuildAudience
                            </Typography>
                        </Typography>
                    </Stack>
                </Container>
            </Box>
        </Box>
    )
}

export default BlogPostFooter